version: '2'
services:
    jhipsterenergysampleapplication-app:
        image: jhipsterenergysampleapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterenergysampleapplication-mysql:3306/jhipsterenergysampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterenergysampleapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipsterenergysampleapplication-mysql
